# Generated by Django 4.1 on 2023-04-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
