# Generated by Django 4.1 on 2023-04-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_entry_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
