# Generated by Django 4.1 on 2023-04-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_remove_entry_views_topic_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.TextField(max_length=100),
        ),
    ]
