# Generated by Django 4.1 on 2023-04-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0009_alter_topic_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
